image: andymeneely/swen331fuzzer
before_script:
    # do not change any of the statements in this section
    - service apache2 start
    - mysql_install_db --user=mysql -ldata=/var/lib/mysql
    - service mysql start
    - /usr/bin/mysqladmin -u root password fuzzer
    - service mysql restart
    - /mysql-setup.sh
    # do not change any of the statements in this section
fuzzrunner:
  script:
    # here is where you can write your commands to run your fuzzer or any custom setup commands
    - echo "hello class"
    # need some example files for vectors and words? These are on the image
    - cat /words.txt
    - cat /vectors.txt

    - sudo apt-get update
    - sudo apt-get install -y --fix-missing libxml2-dev libxslt1-dev
    - pip3 install lxml
    - pip3 install mechanicalsoup
    - pip3 install requests --upgrade
    # python3 fuzzer.py discover http://localhost/ --custom-auth=dvwa --common-words=common_words.txt
    - python3 fuzzer.py test http://localhost:8080 --custom-auth=dvwa --common-words=common_words.txt --vectors=vectors.txt --sensitive=sensitive.txt
    # An example fuzzer command. Note the url is DIFFERENT than XAMPP example (no /dvwa).
    # ruby fuzzer.rb discover http://localhost/ --custom-auth=dvwa
    # python fuzzer.py discover http://localhost/ --custom-auth=dvwa
  stage: test